export const msgPublicOption={
    addBtn:false,
    editBtn:false,
    columnBtn:false,
    refreshBtn:false,
    index:true,
    indexLabel:"序号",
    selection:true,
    delBtn:false,
    column:[{
      label:'姓名',
      prop:'name',
    },{
      label:'性别',
      prop:'sex',
      dicData:[{
        label:'男',value:1
      },{
        label:'女',value:2
      }]
    },{
      label:'联系电话',
      prop:'telephone',
    },{
      label:'岗位',
      prop:'position',
    },{
      label:'部门',
      prop:'deptName',
    }
  ],
  }